name: Build Module

on:
  workflow_dispatch:
  push:

jobs:
  build-ko:
    name: Build module
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/ylarod/ddk-min:android16-6.12-20260313
      options: --privileged

    steps:
    - name: Build 
      run: |
        cd /opt/ddk/src/android16-6.12
        ./scripts/config --file $KDIR/.config -m CONFIG_IP_SET -m CONFIG_IP_SET_HASH_NET -m CONFIG_IP_SET_LIST_SET
        make O=$KDIR olddefconfig
        make O=$KDIR M=$(realpath ./net/netfilter/ipset) modules

    - name: Upload kernel modules
      uses: actions/upload-artifact@v7
      with:
        name: ipset_kos
        path: /opt/ddk/src/android16-6.12/net/netfilter/ipset/*.ko
